import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: '🧬 基礎知識',
      collapsed: false,
      items: [
        'basics/biology-fundamentals',
        'basics/bioinformatics-vs-synthetic-biology',
        'basics/what-is-mrna',
        'basics/e-coli-why-so-important',
        'basics/plasmid-design-practice',
      ],
    },
    {
      type: 'category',
      label: '📚 講義',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Week 1: DNA複製',
          items: [
            'lectures/week1/dna-replication-part1',
            'lectures/week1/dna-replication-part1-detailed',
            'lectures/week1/dna-replication-part2',
            'lectures/week1/dna-replication-part3',
            'lectures/week1/dna-replication-part4',
          ],
        },
        {
          type: 'category',
          label: 'Week 2: モチーフ発見',
          items: [
            'lectures/week2/motif-finding-part1',
            'lectures/week2/motif-finding-part1-detailed',
            'lectures/week2/randomized-motif-search-detailed',
            'lectures/week2/gibbs-sampler-detailed',
            'lectures/week2/laplace-and-chip-seq-detailed',
            'lectures/week2/understanding-motif-and-drug-discovery',
            'lectures/week2/motif-finding-part2',
            'lectures/week2/motif-finding-part3',
            'lectures/week2/quiz-week3',
          ],
        },
        {
          type: 'category',
          label: 'Week 3: ゲノムアセンブリ',
          items: [
            'lectures/week3/genome-sequencing-intro',
            'lectures/week3/genome-assembly-intro',
            'lectures/week3/newspaper-explosion-problem',
            'lectures/week3/string-reconstruction-problem',
            'lectures/week3/hamiltonian-path-problem',
            'lectures/week3/euler-path-problem',
            'lectures/week3/genome-assembly-euler',
          ],
        },
        {
          type: 'category',
          label: 'Week 4: ゲノムアセンブリと抗生物質',
          items: [
            'lectures/week4/de-bruijn-graph',
            'lectures/week4/euler-theorem',
            'lectures/week4/read-pair-assembly',
            'lectures/week4/de-bruijn-reality',
            'lectures/week4/return-to-konigsberg',
            'lectures/week4/antibiotic-discovery',
            'lectures/week4/bacterial-antibiotic-production',
            'lectures/week4/mass-spectrometry-sequencing',
            'lectures/week4/brute-force-cyclopeptide',
            'lectures/week4/branch-and-bound',
            'lectures/week4/error-tolerant-peptide-sequencing',
            'lectures/week4/non-standard-amino-acids',
            'lectures/week4/spectral-convolution',
          ],
        },
        {
          type: 'category',
          label: 'Bioinformatics III: 配列比較とゲノム再配列',
          items: [
            'lectures/bioinformatics3/course-introduction',
            'lectures/bioinformatics3/sequence-comparison-to-biological-insights',
            'lectures/bioinformatics3/alignment-game-and-lcs',
            'lectures/bioinformatics3/manhattan-tourist-problem',
            'lectures/bioinformatics3/from-manhattan-to-alignment-graphs',
            'lectures/bioinformatics3/global-to-local-alignment',
            'lectures/bioinformatics3/affine-gap-penalties',
            'lectures/bioinformatics3/space-efficient-alignment',
            'lectures/bioinformatics3/multiple-sequence-alignment',
            'lectures/bioinformatics3/genome-rearrangements-man-to-mouse',
            'lectures/bioinformatics3/sorting-by-reversals',
            'lectures/bioinformatics3/sorting-by-reversals-implementation',
            'lectures/bioinformatics3/breakpoint-theorem',
            'lectures/bioinformatics3/tumor-genome-rearrangements',
            'lectures/bioinformatics3/two-break-distance',
            'lectures/bioinformatics3/breakpoint-graph-detailed',
            'lectures/bioinformatics3/two-break-theorem-detailed',
            'lectures/bioinformatics3/fragile-breakage-model-detailed',
            'lectures/bioinformatics3/change-problem-dynamic-programming',
          ],
        },
        {
          type: 'category',
          label: 'Bioinformatics IV: 分子進化',
          items: [
            'lectures/bioinformatics4/course-introduction-molecular-evolution',
            'lectures/bioinformatics4/fastest-outbreak',
            'lectures/bioinformatics4/distance-matrix-to-tree',
            'lectures/bioinformatics4/distance-based-phylogeny-algorithm',
            'lectures/bioinformatics4/additive-phylogeny',
            'lectures/bioinformatics4/least-squares-phylogeny',
            'lectures/bioinformatics4/ultrametric-trees-upgma',
            'lectures/bioinformatics4/neighbor-joining-detailed',
            'lectures/bioinformatics4/character-based-phylogeny',
            'lectures/bioinformatics4/small-parsimony-algorithm',
            'lectures/bioinformatics4/large-parsimony-algorithm',
            'lectures/bioinformatics4/modern-phylogeny-applications',
            'lectures/bioinformatics4/paleontology-meets-computing',
          ],
        },
        {
          type: 'category',
          label: 'Bioinformatics V: 質量分析',
          items: [
            'lectures/bioinformatics5/ideal-spectrum-decoding',
            'lectures/bioinformatics5/peptide-sequencing-algorithms',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 アルゴリズム',
      collapsed: false,
      items: [
        'algorithms/frequent-words',
        'algorithms/gc-skew',
        'algorithms/frequent-words-mismatches',
        'algorithms/leaderboard-cyclopeptide-sequencing',
      ],
    },
    {
      type: 'category',
      label: '🚀 先端技術',
      collapsed: false,
      items: [
        'advanced/state-and-ai-in-biology',
        'advanced/mrna-vaccine-development',
        'advanced/drug-discovery-limits-and-synthetic-biology',
      ],
    },
    {
      type: 'category',
      label: '📖 参考資料',
      collapsed: true,
      items: ['resources/glossary'],
    },
  ],
};

export default sidebars;
